backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;
use backend\models\Districts;
use backend\models\Employees;
use backend\models\Blocks;
use backend\models\Donation;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

/**
 * Site controller
 */
class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'ajax-get-blocks', 'ajax-get-employees'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {

        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        /* ---- Code to import employees data into system----- */
//        $emoployeeModel = new Employees();
//        $districtModel = new Districts();
//        $blockModel = new Blocks();
//        $inputFileName = Yii::getAlias('@uploads') . '/Book1.xlsx';
//        $inputFileType = 'Xlsx';
//
//        $reader = IOFactory::createReaderForFile($inputFileName);
//        $reader->setReadDataOnly(true);
//        $spreadsheet = $reader->load($inputFileName);
//        $maxRow = $spreadsheet->getActiveSheet()->getHighestDataRow();
//        if ($maxRow > 20000) {
//            exit('to many rows.');
//        }
//        $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
//        $resultData = array();
//        unset($sheetData[1]);
//        $counter = 0;
//        foreach ($sheetData as $employeeData) {
//            if ($maxRow == $counter) {
//                break;
//            }
//            if (!empty($employeeData['M'])) {
//                $districtId = Districts::findOne(['district_name' => $employeeData['E']]);
//                $blockId = Blocks::findOne(['block_name' => $employeeData['F']]);
//                $resultData[$counter]['emp_id'] = $employeeData['M'];
//                $resultData[$counter]['emp_name'] = $employeeData['I'];
//                $resultData[$counter]['school_name'] = $employeeData['C'];
//                $resultData[$counter]['district'] = (isset($districtId['id']) ? $districtId['id'] : '');
//                $resultData[$counter]['block'] = (isset($blockId['id']) ? $blockId['id'] : '');
//                $resultData[$counter]['contact_number'] = $employeeData['N'];
//                $resultData[$counter]['employee_email'] = '';
//            }
//            $counter++;
//        }
//
//        Yii::$app->db->createCommand()->batchInsert('employees', ['emp_id', 'emp_name', 'school_name', 'district', 'block', 'contact_number', 'employee_email'], $resultData)->execute();
        /* ------ Import code END------------- */


        $district = new Districts();
        $block = new Blocks();
        $employess = new Employees();
        $Donation = new Donation();
        $postedEmployeeId = '';
        $postedDistrictId = '';
        $postedBlockId = '';
        if (Yii::$app->request->post()) {
            $postedDistrictId = Yii::$app->request->post('Districts')['id'];
            $postedBlockId = Yii::$app->request->post('Blocks')['id'];
            $postedEmployeeId = Yii::$app->request->post('Employees')['id'];
        }
        $dataProvider = $Donation->search(Yii::$app->request->queryParams, $postedEmployeeId, $postedDistrictId, $postedBlockId);
        return $this->render('index', ['district' => $district, 'block' => $block, 'employess' => $employess, 'dataProvider' => $dataProvider]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset() {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }
        return $this->render('requestPasswordResetToken', [
                    'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token) {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved successfully.');
            return $this->goHome();
        }
        return $this->render('resetPassword', [
                    'model' => $model,
        ]);
    }

    public function actionAjaxGetBlocks() {
        if (Yii::$app->request->post('districtId') != '') {
            $result = Blocks::find()->where(['district_id' => Yii::$app->request->post('districtId')])->asArray()->all();
            $data['result'] = $result;
        } else {
            $data['result'] = "";
        }

        // return Json    
        return \yii\helpers\Json::encode($data);
    }

    public function actionAjaxGetEmployees() {
        if (Yii::$app->request->get('districtId') != '' && Yii::$app->request->get('blockId') != '') {
            $result = Employees::find()->where(['district' => Yii::$app->request->get('districtId')])->andWhere(['block' => Yii::$app->request->get('blockId')])->asArray()->all();
            $data['result'] = $result;
        } else {
            $data['result'] = "";
        }

        // return Json    
        return \yii\helpers\Json::encode($data);
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/error.php
<?php
/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;

?>
<div class="error">
    <div class="container-floud">
        <div class="col-xs-12 ground-color text-center">
            <div class="container-error-404">
                <div class="clip"><div class="shadow"><span class="digit thirdDigit"></span></div></div>
                <div class="clip"><div class="shadow"><span class="digit secondDigit"></span></div></div>
                <div class="clip"><div class="shadow"><span class="digit firstDigit"></span></div></div>
                <div class="msg">OH!<span class="triangle"></span></div>
            </div>
            <h2 class="h1">Sorry! Page not found</h2>
        </div>
    </div>
</div>
<script src="<?= Yii::$app->params['siteUrl'] ?>js/error.js"></script>

backend/views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\widgets\Breadcrumbs;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\grid\GridView;
use fedemotta\datatables\DataTables;

$this->title = 'Dashboard';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
    <h1><?= $this->title; ?></h1>
    <?=
    Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]);

    /* ------ Get Districts Data----- */
    $districtData = ArrayHelper::map(\backend\models\Districts::find()->asArray()->all(), 'id', 'district_name');
//    echo "<pre>";
//    print_r($districtData);
//    exit;
    ?>

    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Search Donations</h3>
                        <div class="box-body">
                            <div class="row">
                                <?php $form = ActiveForm::begin(['id' => 'filter-donation']); ?>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <?php
                                        if (isset($_POST['Districts'])) {
                                            $district->id = $_POST['Districts']['id'];
                                        }
                                        ?>
                                        <?= $form->field($district, 'id')->dropDownList($districtData, ['prompt' => 'Select District'])->label('District'); ?>
                                        <?= Html::hiddenInput('block_url', \Yii::$app->getUrlManager()->createUrl('site/ajax-get-blocks'), ['id' => 'block-url']) ?>
                                        <?= Html::hiddenInput('employee_url', \Yii::$app->getUrlManager()->createUrl('site/ajax-get-employees'), ['id' => 'ajax-employee-url']) ?>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <?= $form->field($block, 'id')->dropDownList(['prompt' => 'Select Block'])->label('Block'); ?>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <?= $form->field($employess, 'id')->dropDownList(['prompt' => 'Select Employee'])->label('Employees'); ?>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary dashboard-button']) ?>
                                </div>
                            </div>
                            <!-- /.row -->
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?=
                DataTables::widget([
                    'dataProvider' => $dataProvider,
                    'clientOptions' => [
                        "responsive" => true,
                    ],
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        'emp_name',
                        'emp_school',
                        'donation_amount',
                        'contribution_year',
                        ['class' => 'yii\grid\ActionColumn',
                            'header' => 'Actions',
                            'template' => '{view}',
                            'buttons' => [
                                'view' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                        'title' => Yii::t('app', 'view'),
                                        'target' => '_blank',
                            ]);
                        },
                            ],
                            'urlCreator' => function ($action, $model, $key, $index) {
                        if ($action === 'view') {
                            $url = 'donation/view?id=' . base64_encode($model->id);
                            return $url;
                        }
                    }
                        ],
                    ],
                ]);
                ?>
            </div>
        </div>
    </section>
</section>
<?php if (isset($_POST['Districts'])) { ?>
    <script>
        $(document).ready(function() {
            $("#districts-id").trigger("change");
            $("#blocks-id option[value='<?php echo $_POST['Blocks']['id']; ?>']").attr("selected", "selected");
        });
    </script>
<?php }
?>

backend/views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\widgets\Alert;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-box">
    <?= Alert::widget() ?>
    <div class="login-logo">
        <img class="site-logo"src="<?= Yii::$app->params['siteUrl'] ?>images/site-logo.png"/>
    </div>

    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

        <div class="form-group has-feedback">
            <?= $form->field($model, 'username')->textInput(['class' => 'form-control', 'placeholder' => 'Username'])->label(false) ?>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>

        <div class="form-group has-feedback">
            <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Password'])->label(false); ?>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>

        <div class="row">
            <div class="col-xs-8">
                <div class="checkbox icheck">
                    <?= $form->field($model, 'rememberMe')->checkbox() ?>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Sign In', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>
        <?php ActiveForm::end(); ?>
        <?= Html::a('I forgot my password', ['site/request-password-reset']) ?>
        <br>
    </div>
</div>

backend/views/site/requestPasswordResetToken.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
?>

<div class="login-box">
    <div class="login-logo">
        <img class="site-logo"src="<?= Yii::$app->params['siteUrl'] ?>images/site-logo.png"/>
    </div>

    <div class="login-box-body">
        <p class="login-box-msg">Please fill out your email. A link to reset password will be sent there.</p>
        <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

        <div class="form-group has-feedback">
            <?= $form->field($model, 'email')->textInput(['autofocus' => true, 'placeholder' => 'Email Address'])->label(FALSE); ?>
            <span class="glyphicon glyphicon-pencil form-control-feedback"></span>
        </div>


        <div class="row">
            <div class="col-xs-8"></div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary btn-block btn-flat']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/resetPassword.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';

?>

<div class="login-box">
    <div class="login-logo">
        <img class="site-logo"src="<?= Yii::$app->params['siteUrl'] ?>images/site-logo.png"/>
    </div>

    <div class="login-box-body">
        <p class="login-box-msg">Please choose your new password:</p>
        <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

        <div class="form-group has-feedback">
            <?= $form->field($model, 'password')->passwordInput(['autofocus' => true, 'placeholder' => 'Password'])->label(FALSE) ?>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>


        <div class="row">
            <div class="col-xs-8"></div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary btn-block btn-flat']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>