backend/models/Donation.php
<?php

namespace backend\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "donation".
 *
 * @property int $id
 * @property int $emp_id
 * @property int $ddo_id
 * @property string $emp_name
 * @property string $emp_school
 * @property string $donation_amount
 * @property string $contribution_year
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 */
class Donation extends \yii\db\ActiveRecord {

    public $start_date;
    public $end_date;
    public $year;

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'donation';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['id', 'emp_id', 'ddo_id', 'emp_name', 'emp_school', 'donation_amount', 'contribution_year', 'emp_email', 'draft_number', 'start_date', 'end_date', 'year'], 'required'],
            [['emp_school', 'status'], 'string'],
            [['donation_amount', 'emp_contact'], 'number'],
            [['emp_email'], 'email'],
            [['contribution_year', 'created_at', 'updated_at', 'description', 'mark_as_delete'], 'safe'],
            [['emp_name'], 'string', 'max' => 255],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'emp_id' => 'Employee ID',
            'ddo_id' => 'DDO ID',
            'emp_name' => 'Employee Name',
            'emp_school' => 'Employee School',
            'emp_email' => 'Employee Email',
            'emp_contact' => 'Employee Contact Number',
            'donation_amount' => 'Donation Amount',
            'contribution_year' => 'Contribution Date',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'description' => 'Description',
            'draft_number' => 'Draft Number',
            'start_date' => 'Start Date',
            'end_date' => 'End Date'
        ];
    }

    public function search($params, $employeeCode, $districtId, $blockId) {
        $query = Donation::find()->where(['=', 'emp_id', $employeeCode])->orderBy(['created_at' => SORT_DESC]);
        if (($districtId != '' && $districtId != 'prompt') && ($blockId == 'prompt')) {
            $query = Donation::find()
                    ->leftJoin('employees', 'employees.emp_id=donation.emp_id')
                    ->where(['=', 'employees.district', $districtId])
                    ->orderBy(['donation.created_at' => SORT_DESC]);
        } else if (($blockId != '' && $blockId != 'prompt') && ($districtId != '' && $districtId != 'prompt') && ($districtId == 'prompt')) {
            $query = Donation::find()
                    ->leftJoin('employees', 'employees.emp_id=donation.emp_id')
                    ->where(['=', 'employees.district', $districtId])
                    ->andWhere(['=', 'employees.block', $blockId])
                    ->orderBy(['donation.created_at' => SORT_DESC]);
        } else if ($employeeCode != 'prompt') {
            $query = Donation::find()
                    ->leftJoin('employees', 'employees.emp_id=donation.emp_id')
                    ->where(['=', 'employees.emp_id', $employeeCode])
                    ->andWhere(['=', 'employees.district', $districtId])
                    ->andWhere(['=', 'employees.block', $blockId])
                    ->orderBy(['created_at' => SORT_DESC]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $dataProvider;
    }

}

backend/controllers/DonationController.php
<?php

namespace backend\controllers;

use yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use backend\models\Donation;
use backend\models\Employees;
use yii\web\NotFoundHttpException;
use kartik\mpdf\Pdf;

class DonationController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'preview', 'update', 'delete', 'view', 'send-email', 'download', 'ajax-get-employees'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $model = new Donation();
        $employeeArray = Employees::find()->select('emp_id')->asArray()->all();
        $employeeId = array();
        foreach ($employeeArray as $values) {
            $employeeId[] = $values['emp_id'];
        }
        if (!empty(Yii::$app->request->post())) {
            $model->load(Yii::$app->request->post());
            $model->contribution_year = date('Y', strtotime(Yii::$app->request->post('Donation')['contribution_year']));
            if ($model->save(false)) {
                Yii::$app->session->setFlash('success', 'Donation added successfully.');
                $lastInsertedId = base64_encode($model->id);
                $this->redirect(['donation/preview', 'id' => $lastInsertedId]);
            } else
                Yii::$app->session->setFlash('error', 'Some error occured, please try agian.');
        }
        return $this->render('index', ['model' => $model, 'employeeArray' => $employeeId]);
    }

    public function actionPreview($id) {
        $donationID = base64_decode($id);
        $donationData = Donation::find()->where(['id' => $donationID])->one();
        return $this->render('preview', ['donation' => $donationData]);
    }

    public function actionUpdate($id) {
        $employeeArray = array('empty');
        $ddoArray = array('empty');
        $empNameArray = array('empty');
        $schoolArray = array('empty');
        $model = $this->findModel(base64_decode($id));
        if (!empty($model->load(Yii::$app->request->post()))) {
            $model->load(Yii::$app->request->post());
            $model->contribution_year = date('Y', strtotime(Yii::$app->request->post('Donation')['contribution_year']));
            if ($model->save(FALSE)) {
                Yii::$app->session->setFlash('success', 'Donation updated successfully.');
                $lastInsertedId = base64_encode($model->id);
                $this->redirect(['donation/preview', 'id' => $lastInsertedId]);
            } else {
                Yii::$app->session->setFlash('error', 'Some error occured, please try agian.');
            }
        }


        return $this->render('update', [
                    'model' => $model,
                    'employeeArray' => $employeeArray,
                    'ddoArray' => $ddoArray,
                    'empNameArray' => $empNameArray,
                    'schoolArray' => $schoolArray
        ]);
    }

    public function actionDelete($id) {
        $model = $this->findModel(base64_decode($id));
        $model->mark_as_delete = 1;
        if ($model->save()) {
            Yii::$app->session->setFlash('success', 'Donation deleted successfully.');
            $this->redirect(['site/index']);
        } else {
            $lastInsertedId = base64_encode($id);
            Yii::$app->session->setFlash('error', 'Some error occured, please try agian.');
            $this->redirect(['donation/preview', 'id' => $lastInsertedId]);
        }
    }

    public function actionView($id) {
        return $this->render('view', [
                    'donation' => $this->findModel(base64_decode($id)),
        ]);
    }

    protected function findModel($id) {
        if (($model = donation::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionSendEmail($id) {
        $content = $this->renderPartial('_donationPDF', [
            'donation' => $this->findModel(base64_decode($id)),
        ]);

        $header = $this->renderPartial('_donationPdfHeader', [
            'donation' => $this->findModel(base64_decode($id)),
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_DOWNLOAD,
            'content' => $content,
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => ['title' => 'Krajee Report Title'],
            'methods' => [
                'SetHeader' => [$header],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);
        $mpdf = $pdf->api;
        $mpdf->SetHeader($header);
        $mpdf->SetFooter('{PAGENO}');
        $mpdf->WriteHtml($content);
        $mpdf->Output(Yii::getAlias('@backend') . '/uploads/temp_pdf/donation-' . base64_decode($id) . '.pdf', 'F');

        /* ------------- Send mail to employee with receipt attachment------------ */
        $donation_details = $this->findModel(base64_decode($id));
        $emailBody = '<html lang="en"><head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body style="margin:0; padding:0; background-color:#FFF;">
  <center>
    <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFF">
    <tr>
    <td align="center" valign="top"><img style="width:10%;" src="' . Yii::$app->params['siteUrl'] . 'images/site-logo.png"/></td>
    </tr>
    </table>
  </center>
    <table width="50%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFF" style="padding: 30px;margin-top: 5%;">
    <tr>
    <tr>
            <td valign="top">Hello ' . $donation_details->emp_name . '</td>
        </tr>
        <td valign="top">&nbsp;</td>
        </tr>
        <tr>
            <td valign="top">Please find the attached donation receipt for contribution year ' . date('Y', strtotime($donation_details->contribution_year)) . '.</td>
        </tr>
        </table>
</body>
</html>';

        Yii::$app->mail->compose()
                ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->name])
                ->setTo('rahulswami482@gmail.com')
                ->setSubject('Hitkari Nidhi - Donation Receipt - ' . date('Y', strtotime($donation_details->contribution_year)))
                ->setHtmlBody($emailBody)
                ->attach(Yii::getAlias('@backend') . '/uploads/temp_pdf/donation-' . base64_decode($id) . '.pdf')
                ->send();

        $donation_details->status = 1;
        unlink(Yii::getAlias('@backend') . '/uploads/temp_pdf/donation-' . base64_decode($id) . '.pdf');
        if ($donation_details->save(false)) {
            Yii::$app->session->setFlash('success', 'Donation receipt successfully sent to employee.');
            $this->redirect(['donation/view', 'id' => $id]);
        } else {
            Yii::$app->session->setFlash('error', 'Some error occured, please try agian.');
            $this->redirect(['donation/preview', 'id' => $id]);
        }
    }

    public function actionDownload($id) {
        $content = $this->renderPartial('_donationPDF', [
            'donation' => $this->findModel(base64_decode($id)),
        ]);

        $header = $this->renderPartial('_donationPdfHeader', [
            'donation' => $this->findModel(base64_decode($id)),
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE,
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_DOWNLOAD,
            'content' => $content,
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => ['title' => 'Krajee Report Title'],
            'methods' => [
                'SetHeader' => [$header],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);
        $mpdf = $pdf->api;
        $mpdf->SetHeader($header);
        $mpdf->SetFooter('{PAGENO}');
        $mpdf->WriteHtml($content);
        $mpdf->Output('donation-' . base64_decode($id) . '.pdf', 'D');
    }

    public function actionAjaxGetEmployees() {
        if (Yii::$app->request->get('employeeCode') != '') {
            $result = Employees::findOne(['emp_id' => Yii::$app->request->get('employeeCode')]);
            $data['result'] = $result;
        } else {
            $data['result'] = "";
        }

        // return Json    
        return \yii\helpers\Json::encode($data);
    }

}

backend/views/donation/_donationPDF.php
<html>
    <body>
        <div style="width:100%">
            <div style="width: 100%;">
                <div style="width: 100%; margin-top: 40px;">
                    <div style="width: 100%; text-align: center;">
                        <h4 style="text-decoration: underline;"><strong>Receipt of Donation</strong></h4>
                    </div>
                    <div style="margin-top: 40px;">
                        <div>
                            <table style="width: 100%;">
                                <tbody>
                                    <tr>
                                        <th style="width:30%; text-align: left; padding: 10px;">Employee Name</th>
                                        <td style="float: left;margin-left: 20%;padding: 10px;"><?= $donation->emp_name; ?></td>
                                    </tr>
                                    <tr>
                                        <th style="width:30%; text-align: left; padding: 10px;">Employee School/Office</th>
                                        <td style="float: left;margin-left: 20%;padding: 10px;"><?= $donation->emp_school; ?></td>
                                    </tr>
                                    <tr>
                                        <th style="width:30%; text-align: left; padding: 10px;">Employee Email</th>
                                        <td style="float: left;margin-left: 20%;padding: 10px;"><?= $donation->emp_email; ?></td>
                                    </tr>
                                </tbody>
                            </table>

                            <table style="margin-top: 30px; border: 1px solid #000; width: 100%; border-collapse:collapse;">
                                <tbody>
                                    <tr>
                                        <th style="width: 20%; border: 1px solid #000; padding: 10px;">Employee ID</th>
                                        <th style="width: 15%; border: 1px solid #000; padding: 10px;">DDO ID</th>
                                        <th style="width: 10%; border: 1px solid #000; padding: 10px;">Amount</th>
                                        <th style="width: 25%; border: 1px solid #000; padding: 10px;">Contribution Year</th>
                                        <th style="width: 15%; border: 1px solid #000; padding: 10px;">Date</th>
                                        <th style="width: 15%; border: 1px solid #000; padding: 10px;">Draft #</th>
                                    </tr>
                                    <tr>
                                        <td style="border: 1px solid #000; padding: 10px; text-align: center;"><?= $donation->emp_id; ?></td>
                                        <td style="border: 1px solid #000; padding: 10px; text-align: center;"><?= $donation->ddo_id; ?></td>
                                        <td style="border: 1px solid #000; padding: 10px; text-align: center;"><?= $donation->donation_amount; ?></td>
                                        <td style="border: 1px solid #000; padding: 10px; text-align: center;"><?= date('Y', strtotime($donation->contribution_year)); ?></td>
                                        <td style="border: 1px solid #000; padding: 10px; text-align: center;"><?= date('d-M-Y', strtotime($donation->created_at)); ?></td>
                                        <td style="border: 1px solid #000; padding: 10px; text-align: center;"><?= $donation->draft_number; ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </body>
</html>

backend/views/donation/_donationPdfHeader.php
<div style="width: 15%; float: left; font-style: normal; text-align: left;">
    <h5>Receipt No. <?= 'RJHN-' . $donation->id; ?></h5>
</div>
<div style="text-align: center; width: 70%; float: left; font-style: normal; ">
    <h3>HITKARI NIDHI<br>Department of Secondary Education<br>Bikaner (Rajasthan)</h3>
</div>
<div style="width: 10%; float: right;">
    <img style="width: 50%;" src="<?= Yii::$app->params['siteUrl'] ?>images/receipt-logo.png">
</div>

backend/views/donation/index.php
<?php
/* @var $this yii\web\View */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use dosamigos\datepicker\DatePicker;
use kartik\typeahead\Typeahead;

$this->title = 'Add Donation';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
    <h1><?= $this->title; ?></h1>
    <?=
    Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]);
    ?>

    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Donation Form</h3>
                        <div class="box-body">
                            <?php $form = ActiveForm::begin(['id' => 'add-donation']); ?>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?=
                                        $form->field($model, 'emp_id')->widget(Typeahead::classname(), [
                                            'dataset' => [
                                                [
                                                    'local' => $employeeArray,
                                                    'limit' => 15
                                                ]
                                            ],
                                            'pluginOptions' => ['highlight' => true],
                                            'options' => ['placeholder' => 'Please Enter Employee ID', 'id' => 'employee_id'],
                                        ]);
                                        ?>
                                        <?= Html::hiddenInput('employee_url', \Yii::$app->getUrlManager()->createUrl('donation/ajax-get-employees'), ['id' => 'ajax_employee_url']) ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $form->field($model, 'ddo_id')->textInput(['placeholder' => 'Please Enter DDO ID', 'id' => 'ddo_id']) ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $form->field($model, 'emp_name')->textInput(['placeholder' => 'Please Enter Employee Name', 'id' => 'employee_name']) ?>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $form->field($model, 'emp_school')->textInput(['placeholder' => 'Please Enter School Name', 'id' => 'school_name']) ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <?= $form->field($model, 'emp_email')->textInput(['placeholder' => 'Please Enter Employee Email', 'id' => 'employee_email']) ?>
                                </div>

                                <div class="col-md-6">
                                    <?= $form->field($model, 'emp_contact')->textInput(['placeholder' => 'Please Enter Employee Contact No.', 'id' => 'employee_contact']) ?>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $form->field($model, 'donation_amount')->textInput(['placeholder' => 'Please Enter Donation Amount', 'id' => 'donation_amount'])
                                        ?>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $form->field($model, 'draft_number')->textInput(['placeholder' => 'Please Enter Draft Number', 'id' => 'draft_number'])
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?= $form->field($model, 'description')->textarea(['placeholder' => 'Please Enter Description, If any....', 'id' => 'description', 'rows' => 4, 'cols' => 5])
                                        ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <?=
                                        $form->field($model, 'contribution_year')->widget(
                                                DatePicker::className(), [
                                            'clientOptions' => [
                                                'autoclose' => true,
                                                'format' => 'dd-M-yyyy'
                                            ]
                                        ]);
                                        ?>
                                    </div>
                                </div>
                            </div>

                            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary pull-right']) ?>
                            <!-- /.row -->
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>

backend/views/donation/preview.php
<?php
/* @var $this yii\web\View */

use yii\widgets\Breadcrumbs;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use dosamigos\datepicker\DatePicker;
use kartik\typeahead\Typeahead;

$this->title = 'Donation Receipt';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
    <h1><?= $this->title; ?></h1>
    <?=
    Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]);
    ?>

    <section class="content">
        <!-- Info boxes -->
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Receipt No. RJHN-<?= $donation->id; ?></h3>
                        <div class="pull-right">
                            <div class="btn-group">
                                <a href="<?= Yii::$app->homeUrl . 'donation/update?id=' . base64_encode($donation->id) . ''; ?>" class="btn bg-maroon btn-sm">Edit</a>
                            </div>
                            <div class="btn-group">
                                <a href="<?= Yii::$app->homeUrl . 'donation/view?id=' . base64_encode($donation->id) . ''; ?>" class="btn bg-purple btn-sm">View</a>
                            </div>
                            <div class="btn-group">
                                <a href="<?= Yii::$app->homeUrl . 'donation/delete?id=' . base64_encode($donation->id) . ''; ?>" class="btn bg-navy btn-sm">Delete</a>
                            </div>
                            <div class="btn-group">
                                <a href="<?= Yii::$app->homeUrl . 'donation/send-email?id=' . base64_encode($donation->id) . ''; ?>" class="btn bg-olive btn-sm">Send Email</a>
                            </div>
                        </div>
                    </div>
                    <div class="box-body receipt-padding">
                        <div class="col-md-11 text-center col-xs-12">
                            <h3 class="remove-top-m">HITKARI NIDHI<br>Department of Secondary Education<br>Bikaner (Rajasthan)</h3>
                        </div>
                        <div class="col-md-1 col-xs-12">
                            <img class="receipt-logo" src="<?= Yii::$app->params['siteUrl'] ?>images/receipt-logo.png"/>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-11 text-center col-xs-12">
                            <h3><strong>Receipt of Donation</strong></h3>
                        </div>
                        <div class="col-md-1">
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-xs-12 margin-top-receipt">
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <th style="width:30%">Employee Name</th>
                                            <td><?= $donation->emp_name; ?></td>
                                        </tr>
                                        <tr>
                                            <th>Employee School/Office</th>
                                            <td><?= $donation->emp_school; ?></td>
                                        </tr>
                                        <tr>
                                            <th>Employee Email</th>
                                            <td><?= $donation->emp_email; ?></td>
                                        </tr>
                                    </tbody>
                                </table>

                                <table class="table table-bordered">
                                    <tbody>
                                        <tr>
                                            <th>Employee ID</th>
                                            <th>DDO ID</th>
                                            <th>Amount</th>
                                            <th>Contribution Year</th>
                                            <th>Date</th>
                                            <th>Draft #</th>
                                        </tr>
                                        <tr>
                                            <td><?= $donation->emp_id; ?></td>
                                            <td><?= $donation->ddo_id; ?></td>
                                            <td><?= $donation->donation_amount; ?></td>
                                            <td><?= $donation->contribution_year; ?></td>
                                            <td><?= date('d-M-Y', strtotime($donation->created_at)); ?></td>
                                            <td><?= $donation->draft_number; ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</section>